title: Wildes Torres da Silva – Portfolio
description: Desenvolvedor Full Stack & BI | Java | SQL | Power BI | React | Python
url: "https://w1torres.github.io"
baseurl: "/professional-profile"
theme: null
